# SwiftLint Configuration for LegacyLense

# Paths to include/exclude
included:
  - LegacyLense

excluded:
  - Pods
  - LegacyLense.xcodeproj
  - LegacyLense.xcworkspace
  - DerivedData
  - .git
  - DeOldify_CoreML_Conversion

# Rules to disable
disabled_rules:
  - trailing_whitespace # Can be noisy during development
  - todo # We want to track TODOs in comments

# Rules to enable that are opt-in
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 100
  error: 150

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level: 2
  function_level: 5

large_tuple:
  warning: 3
  error: 4

# Identifier naming rules
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 45
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 45
    error: 60

# Force unwrapping configuration
force_unwrapping:
  severity: warning

# Multiline arguments
multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true

# Trailing comma
trailing_comma:
  mandatory_comma: true

# Custom rules
custom_rules:
  # Detect potential memory leaks
  weak_delegate:
    name: "Weak Delegate"
    regex: "delegate\\s*:\\s*[^?]*\\?"
    message: "Delegates should be weak to prevent retain cycles"
    severity: warning

  # Detect force casting
  force_cast_warning:
    name: "Force Cast Warning"
    regex: "as!"
    message: "Prefer safe casting with 'as?' over force casting with 'as!'"
    severity: warning

  # Detect print statements (should use proper logging)
  no_print:
    name: "No Print Statements"
    regex: "\\bprint\\s*\\("
    message: "Use proper logging instead of print statements"
    severity: warning

  # Detect TODO/FIXME without context
  todo_fixme_context:
    name: "TODO/FIXME Context"
    regex: "(TODO|FIXME)(?!:)"
    message: "TODO and FIXME should include context: // TODO: description"
    severity: warning

  # Detect hardcoded strings that should be localized
  hardcoded_strings:
    name: "Hardcoded Strings"
    regex: 'Text\s*\(\s*"[^"]*"\s*\)'
    message: "Consider using localized strings for user-facing text"
    severity: warning
    
# Reporter
reporter: "xcode"